version: '3'
services:
  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto/config:/mosquitto/config
    networks:
      - mqtt-network
    
  base_station:
    build: 
      context: ./
      dockerfile: Dockerfile.base_station                                          
    container_name: mqtt-bs
    depends_on:
      - mqtt-broker
    volumes:
      - /home/vincenzo/simulazione_osm/simulazione.osm:/app/simulazione.osm
    networks:
      - mqtt-network

  base_station2:
    build: 
      context: ./
      dockerfile: Dockerfile.base_station                                          
    container_name: mqtt-bs2
    depends_on:
      - mqtt-broker
    volumes:
      - /home/vincenzo/simulazione_osm/simulazione.osm:/app/simulazione.osm
    networks:
      - mqtt-network

  veicolo:
    build: 
      context: ./
      dockerfile: Dockerfile.veicolo
    container_name: mqtt-veicolo
    depends_on:
      - mqtt-broker
    volumes:
      - /home/vincenzo/simulazione_osm/simulazione.osm:/app/simulazione.osm
      - /home/vincenzo/simulazione_osm/simulazione.rou.xml:/app/simulazione.rou.xml
      - /home/vincenzo/simulazione_osm/simulazione.sumocfg:/app/simulazione.sumocfg
      - /home/vincenzo/simulazione_osm/simulazione.net.xml:/app/simulazione.net.xml
    networks:
      - mqtt-network

networks:
  mqtt-network:
    driver: bridge
