version: '3'
services:
  amqp-broker:
    image: rabbitmq
    container_name: amqp-broker
    ports:
      - 5672:5672
      
    volumes:
      - ./rabbitmq/config:/rabbitmq/config
    networks:
      - amqp-network
    
    

  base_station:
    build: 
      context: ./
      dockerfile: Dockerfile.base_station                                          
    container_name: amqp-bs
    depends_on:
      - amqp-broker
    volumes:
      - /home/vincenzo/Simulazione/Stadio.osm:/app/Stadio.osm
    networks:
      - amqp-network
    

  veicolo:
    build: 
      context: ./
      dockerfile: Dockerfile.veicolo
    container_name: amqp-veicolo
    depends_on:
      - amqp-broker
    volumes:
      - /home/vincenzo/Simulazione/Stadio.osm:/app/Stadio.osm
      - /home/vincenzo/Simulazione/Stadio.rou.xml:/app/Stadio.rou.xml
      - /home/vincenzo/Simulazione/Stadio.sumocfg:/app/Stadio.sumocfg
      - /home/vincenzo/Simulazione/Stadio.net.xml:/app/Stadio.net.xml
    environment:
      - SUMO_HOME=/usr/share/sumo  # Assicurati di mettere il percorso corretto
    networks:
      - amqp-network
   

networks:
  amqp-network:
    driver: bridge