version: '3'
services:
  amqp-broker:
    image: rabbitmq
    container_name: amqp-broker
    ports:
      - 5672:5672
      
    volumes:
      - ./rabbitmq/config:/rabbitmq/config
    networks:
      - amqp-network
    
    

  base_station:
    build: 
      context: ./
      dockerfile: Dockerfile.base_station                                          
    container_name: amqp-bs
    depends_on:
      - amqp-broker
    volumes:
      - /home/vincenzo/simulazione_osm/simulazione.osm:/app/simulazione.osm
    networks:
      - amqp-network
    

  veicolo:
    build: 
      context: ./
      dockerfile: Dockerfile.veicolo
    container_name: amqp-veicolo
    depends_on:
      - amqp-broker
    volumes:
      - /home/vincenzo/simulazione_osm/simulazione.osm:/app/simulazione.osm
      - /home/vincenzo/simulazione_osm/simulazione.rou.xml:/app/simulazione.rou.xml
      - /home/vincenzo/simulazione_osm/simulazione.sumocfg:/app/simulazione.sumocfg
      - /home/vincenzo/simulazione_osm/simulazione.net.xml:/app/simulazione.net.xml
    environment:
      - SUMO_HOME=/usr/share/sumo  # Assicurati di mettere il percorso corretto
    networks:
      - amqp-network
   

networks:
  amqp-network:
    driver: bridge